version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./deployment/api.Dockerfile
    image: musifier:${BUILD_NUMBER}
    container_name: musifier-${BRANCH_NAME}
    environment:
      - API_PORT
      - HOST
      - DATABASE_HOST
      - DATABASE_PORT=5432
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_NAME
      - SPOTIFY_AUTH_BASE_URL
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
      - SYNC_CRON_TIME
      - CACHE_PATH
      - DISABLE_SYNC
    restart: always
    ports:
      - '${API_PORT}:5000'
    volumes:
      - /opt/musifier/data-${BRANCH_NAME}:/usr/src/musifier/public:rw
      - /opt/musifier/images-${BRANCH_NAME}/:/home/node/apps/api/uploads:rw
      - /opt/musifier/music-cache-${BRANCH_NAME}:/home/node/apps/api/cache:rw
  web:
    build:
      context: .
      dockerfile: ./deployment/web.Dockerfile
      args:
        - BACKEND_URL=${BACKEND_URL}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
    image: musifier_web:${BUILD_NUMBER}
    container_name: musifier_web-${BRANCH_NAME}
    restart: always
    environment:
      - BACKEND_URL=${BACKEND_URL}
    ports:
      - '${PORT_NUMBER_FRONT}:3000'
    volumes:
      - /opt/musifier_web/logs-${BRANCH_NAME}:/usr/src/musifier_web/logs:rw
      - /opt/musifier_web/data-${BRANCH_NAME}:/usr/src/musifier_web/public:rw
  db:
    image: postgres:11.2-alpine
    container_name: musifier-db-${BRANCH_NAME}
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./musifier/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
      - /opt/musifier-db-${BRANCH_NAME}:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:5432'

  # proxy-web:
  #   image: darknet00/bore-proxy
  #   environment:
  #       - SERVER_HOST=${PROXY_SERVER_HOST}
  #       - LOCAL_HOST=${PROXY_CLIENT_HOST}
  #       - SECRET=${PROXY_SECRET}
  #       - PORT=${PORT_NUMBER_FRONT}
  #   container_name: musifier-proxy-web-${BRANCH_NAME}
  #   restart: always
  # proxy-api:
  #   image: darknet00/bore-proxy
  #   environment:
  #       - SERVER_HOST=${PROXY_SERVER_HOST}
  #       - LOCAL_HOST=${PROXY_CLIENT_HOST}
  #       - SECRET=${PROXY_SECRET}
  #       - PORT=${PORT}
  #   container_name: musifier-proxy-api-${BRANCH_NAME}
  #   restart: always
  #
